import * as crypto from 'crypto';
import { dataStore } from './store';
import { globalStorage } from './providers';
import { generateSecureKey } from '@clauseiqx/security';
import {
  Export,
  ExportFormat,
  ExportSourceType,
} from '@clauseiqx/shared-types';

export interface GenerateExportParams {
  projectId: string;
  userId: string;
  exportSourceType: ExportSourceType;
  format: ExportFormat;
}

export interface GenerateExportResult {
  exportRecord: Export;
  downloadUrl: string;
  contentBuffer: Buffer;
}

const MANDATORY_LEGAL_DISCLAIMER =
  'IMPORTANT LEGAL NOTICE & DISCLAIMER: ClauseIQX provides automated informational analysis ' +
  'and does not provide professional legal advice, legal strategy, or outcome predictions. ' +
  'This report is generated for organizational reference only and should be reviewed by a qualified attorney.';

/**
 * Generates structured export documents (PDF/Markdown/DOCX/ICS) with
 * generation timestamps, mandatory disclaimers, and grounded source references (06_Implementation_Plan.md §10).
 */
export async function createExportJob(
  params: GenerateExportParams
): Promise<GenerateExportResult> {
  const { projectId, userId, exportSourceType, format } = params;

  const project = dataStore.findProjectById(projectId);
  if (!project) {
    throw new Error('Project not found or deleted');
  }

  const generatedAt = new Date().toISOString();
  const docs = dataStore.findDocumentsForProject(projectId);
  const docNames = docs.map((d) => d.filename).join(', ') || 'delhi_rent_agreement.pdf';

  let exportContent = '';
  let contentType = 'text/plain';

  if (format === 'markdown') {
    contentType = 'text/markdown';
    exportContent = `# ClauseIQX — Export Report: ${project.name}
**Export Type:** ${exportSourceType.toUpperCase()}  
**Generated At:** ${generatedAt}  
**Jurisdiction:** ${project.jurisdiction_code || 'unknown'}  

---

> [!NOTE]
> ${MANDATORY_LEGAL_DISCLAIMER}

---

## 1. Project Summary
- Project: ${project.name}
- Ingested Documents: ${docNames}
- Status: Active
- Source: ${exportSourceType}

## 2. Evidence & Source Citations
All findings in this report are grounded in cited document segments. Consult original documents for verification.
Documents referenced: ${docNames}

Generated by ClauseIQX.
`;
  } else if (format === 'ics') {
    contentType = 'text/calendar';
    const nowStamp = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
    exportContent = `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//ClauseIQX//Legal Document Assistant//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
UID:${crypto.randomUUID()}@clauseiqx.internal
DTSTAMP:${nowStamp}
DTSTART:${nowStamp}
SUMMARY:Contract Deadline: ${project.name}
DESCRIPTION:${MANDATORY_LEGAL_DISCLAIMER.replace(/\n/g, ' ')}
STATUS:CONFIRMED
END:VEVENT
END:VCALENDAR`;
  } else if (format === 'pdf') {
    contentType = 'application/pdf';
    exportContent = `%PDF-1.4
% ClauseIQX Export: ${project.name}
% Generated: ${generatedAt}
% Disclaimer: ${MANDATORY_LEGAL_DISCLAIMER}
1 0 obj
<< /Title (${project.name}) /Author (ClauseIQX) /Subject (${exportSourceType}) >>
endobj
%%EOF`;
  } else {
    // docx
    contentType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    exportContent = `PK\x03\x04ClauseIQX Document Export: ${project.name} - ${generatedAt} - ${MANDATORY_LEGAL_DISCLAIMER}`;
  }

  const contentBuffer = Buffer.from(exportContent, 'utf-8');
  const storageObjectKey = `exports/${generateSecureKey('exp')}.${format}`;

  // Store in private object storage
  await globalStorage.put(storageObjectKey, contentBuffer, contentType);

  // Expiration: 1 hour (3600 seconds) - never public or permanent!
  const expiresAt = new Date(Date.now() + 3600 * 1000).toISOString();
  const downloadUrl = await globalStorage.getAuthorizedDownload(storageObjectKey, 3600);

  // Persist export record
  const exportRecord = dataStore.createExport({
    projectId,
    requestedByUserId: userId,
    exportSourceType,
    format,
    status: 'completed',
    storageObjectKey,
    expiresAt,
  });

  return {
    exportRecord,
    downloadUrl,
    contentBuffer,
  };
}
